import type { CountryTableRow } from "./types";

/** Seed data — replace with GET /v1/countries (or similar) when available. */
export const countriesMockData: CountryTableRow[] = [
  {
    id: "1",
    flagEmoji: "🇬🇧",
    name: "United Kingdom",
    isoCode: "GB",
    continent: "Europe",
    universities: 164,
    status: "ACTIVE",
  },
  {
    id: "2",
    flagEmoji: "🇨🇦",
    name: "Canada",
    isoCode: "CA",
    continent: "North America",
    universities: 96,
    status: "ACTIVE",
  },
  {
    id: "3",
    flagEmoji: "🇦🇺",
    name: "Australia",
    isoCode: "AU",
    continent: "Oceania",
    universities: 43,
    status: "ACTIVE",
  },
  {
    id: "4",
    flagEmoji: "🇺🇸",
    name: "United States",
    isoCode: "US",
    continent: "North America",
    universities: 210,
    status: "ACTIVE",
  },
  {
    id: "5",
    flagEmoji: "🇮🇳",
    name: "India",
    isoCode: "IN",
    continent: "Asia",
    universities: 112,
    status: "ACTIVE",
  },
  {
    id: "6",
    flagEmoji: "🇩🇪",
    name: "Germany",
    isoCode: "DE",
    continent: "Europe",
    universities: 89,
    status: "ACTIVE",
  },
  {
    id: "7",
    flagEmoji: "🇫🇷",
    name: "France",
    isoCode: "FR",
    continent: "Europe",
    universities: 76,
    status: "ACTIVE",
  },
  {
    id: "8",
    flagEmoji: "🇳🇿",
    name: "New Zealand",
    isoCode: "NZ",
    continent: "Oceania",
    universities: 28,
    status: "ACTIVE",
  },
  {
    id: "9",
    flagEmoji: "🇮🇪",
    name: "Ireland",
    isoCode: "IE",
    continent: "Europe",
    universities: 22,
    status: "ACTIVE",
  },
  {
    id: "10",
    flagEmoji: "🇸🇬",
    name: "Singapore",
    isoCode: "SG",
    continent: "Asia",
    universities: 18,
    status: "ACTIVE",
  },
  {
    id: "11",
    flagEmoji: "🇿🇦",
    name: "South Africa",
    isoCode: "ZA",
    continent: "Africa",
    universities: 26,
    status: "INACTIVE",
  },
  {
    id: "12",
    flagEmoji: "🇧🇷",
    name: "Brazil",
    isoCode: "BR",
    continent: "South America",
    universities: 54,
    status: "INACTIVE",
  },
  {
    id: "13",
    flagEmoji: "🇯🇵",
    name: "Japan",
    isoCode: "JP",
    continent: "Asia",
    universities: 121,
    status: "INACTIVE",
  },
  {
    id: "14",
    flagEmoji: "🇲🇾",
    name: "Malaysia",
    isoCode: "MY",
    continent: "Asia",
    universities: 34,
    status: "INACTIVE",
  },
  {
    id: "15",
    flagEmoji: "🇦🇪",
    name: "United Arab Emirates",
    isoCode: "AE",
    continent: "Asia",
    universities: 41,
    status: "INACTIVE",
  },
];
