import type { ApplicationRecord } from "./types";

/** Seed list — replace with API when available. */
export const applicationsMockData: ApplicationRecord[] = [
  {
    id: "APP-001",
    studentName: "Aarav Sharma",
    studentEmail: "aarav.sharma@email.com",
    partnerName: "EduNext",
    counsellorName: "Priya Mehta",
    university: "University of Manchester",
    program: "MSc Computer Science",
    intake: "Sep 2025",
    stage: "Enrolled",
    submittedAt: "2025-01-10",
  },
  {
    id: "APP-002",
    studentName: "Sneha Patel",
    studentEmail: "sneha.patel@email.com",
    partnerName: "Global Reach",
    counsellorName: "Rahul Verma",
    university: "Imperial College London",
    program: "MEng Electrical Engineering",
    intake: "Jan 2026",
    stage: "Offer Received",
    submittedAt: "2025-01-08",
  },
  {
    id: "APP-003",
    studentName: "Vikram Singh",
    studentEmail: "vikram.singh@email.com",
    partnerName: "EduNext",
    counsellorName: "Priya Mehta",
    university: "University of Edinburgh",
    program: "MBA",
    intake: "Sep 2025",
    stage: "Sent To University",
    submittedAt: "2025-01-05",
  },
  {
    id: "APP-004",
    studentName: "Ananya Reddy",
    studentEmail: "ananya.reddy@email.com",
    partnerName: "Study Abroad Co",
    counsellorName: "Kavita Nair",
    university: "University of Warwick",
    program: "MSc Data Science",
    intake: "Sep 2025",
    stage: "GS Approved",
    submittedAt: "2025-01-04",
  },
  {
    id: "APP-005",
    studentName: "Rohan Kapoor",
    studentEmail: "rohan.kapoor@email.com",
    partnerName: "EduNext",
    counsellorName: "Priya Mehta",
    university: "King's College London",
    program: "LLM International Law",
    intake: "Jan 2026",
    stage: "Pending GS",
    submittedAt: "2025-01-03",
  },
  {
    id: "APP-006",
    studentName: "Ishita Gupta",
    studentEmail: "ishita.gupta@email.com",
    partnerName: "Global Reach",
    counsellorName: "Rahul Verma",
    university: "University of Bristol",
    program: "BSc Economics",
    intake: "Sep 2025",
    stage: "RM Review",
    submittedAt: "2025-01-02",
  },
  {
    id: "APP-007",
    studentName: "Karan Malhotra",
    studentEmail: "karan.malhotra@email.com",
    partnerName: "Study Abroad Co",
    counsellorName: "Kavita Nair",
    university: "University of Leeds",
    program: "MSc Finance",
    intake: "Sep 2025",
    stage: "Partner Review",
    submittedAt: "2024-12-28",
  },
  {
    id: "APP-008",
    studentName: "Meera Joshi",
    studentEmail: "meera.joshi@email.com",
    partnerName: "EduNext",
    counsellorName: "Priya Mehta",
    university: "University of Glasgow",
    program: "MSc Public Health",
    intake: "Jan 2026",
    stage: "Draft",
    submittedAt: "2024-12-20",
  },
  {
    id: "APP-009",
    studentName: "Aditya Rao",
    studentEmail: "aditya.rao@email.com",
    partnerName: "Global Reach",
    counsellorName: "Rahul Verma",
    university: "University of Sheffield",
    program: "PhD Materials Science",
    intake: "Sep 2025",
    stage: "Rejected",
    submittedAt: "2024-12-15",
  },
  {
    id: "APP-010",
    studentName: "Neha Krishnan",
    studentEmail: "neha.krishnan@email.com",
    partnerName: "EduNext",
    counsellorName: "Priya Mehta",
    university: "University of Birmingham",
    program: "MSc Artificial Intelligence",
    intake: "Sep 2025",
    stage: "Enrolled",
    submittedAt: "2024-12-10",
  },
  {
    id: "APP-011",
    studentName: "Arjun Desai",
    studentEmail: "arjun.desai@email.com",
    partnerName: "Study Abroad Co",
    counsellorName: "Kavita Nair",
    university: "University of Nottingham",
    program: "MSc Mechanical Engineering",
    intake: "Jan 2026",
    stage: "Partner Review",
    submittedAt: "2025-01-11",
  },
  {
    id: "APP-012",
    studentName: "Pooja Iyer",
    studentEmail: "pooja.iyer@email.com",
    partnerName: "Global Reach",
    counsellorName: "Rahul Verma",
    university: "University of Southampton",
    program: "MSc Cyber Security",
    intake: "Sep 2025",
    stage: "RM Review",
    submittedAt: "2025-01-09",
  },
  {
    id: "APP-013",
    studentName: "Siddharth Menon",
    studentEmail: "siddharth.menon@email.com",
    partnerName: "EduNext",
    counsellorName: "Priya Mehta",
    university: "University of York",
    program: "BA Psychology",
    intake: "Sep 2025",
    stage: "Sent To University",
    submittedAt: "2025-01-07",
  },
  {
    id: "APP-014",
    studentName: "Divya Nair",
    studentEmail: "divya.nair@email.com",
    partnerName: "Study Abroad Co",
    counsellorName: "Kavita Nair",
    university: "University of Liverpool",
    program: "MSc Marketing",
    intake: "Jan 2026",
    stage: "GS Approved",
    submittedAt: "2025-01-06",
  },
  {
    id: "APP-015",
    studentName: "Harsh Tiwari",
    studentEmail: "harsh.tiwari@email.com",
    partnerName: "Global Reach",
    counsellorName: "Rahul Verma",
    university: "Queen Mary University",
    program: "MSc Business Analytics",
    intake: "Sep 2025",
    stage: "Pending GS",
    submittedAt: "2025-01-01",
  },
  {
    id: "APP-016",
    studentName: "Riya Saxena",
    studentEmail: "riya.saxena@email.com",
    partnerName: "EduNext",
    counsellorName: "Priya Mehta",
    university: "University of Exeter",
    program: "MSc Environmental Science",
    intake: "Sep 2025",
    stage: "Draft",
    submittedAt: "2024-12-30",
  },
  {
    id: "APP-017",
    studentName: "Manish Agarwal",
    studentEmail: "manish.agarwal@email.com",
    partnerName: "Study Abroad Co",
    counsellorName: "Kavita Nair",
    university: "Cardiff University",
    program: "MSc Architecture",
    intake: "Jan 2026",
    stage: "Offer Received",
    submittedAt: "2024-12-22",
  },
  {
    id: "APP-018",
    studentName: "Tanvi Bhatt",
    studentEmail: "tanvi.bhatt@email.com",
    partnerName: "Global Reach",
    counsellorName: "Rahul Verma",
    university: "University of Sussex",
    program: "MA Media Studies",
    intake: "Sep 2025",
    stage: "RM Review",
    submittedAt: "2024-12-18",
  },
  {
    id: "APP-019",
    studentName: "Nikhil Chopra",
    studentEmail: "nikhil.chopra@email.com",
    partnerName: "EduNext",
    counsellorName: "Priya Mehta",
    university: "University of Durham",
    program: "MSc Physics",
    intake: "Sep 2025",
    stage: "GS Approved",
    submittedAt: "2024-12-12",
  },
  {
    id: "APP-020",
    studentName: "Shreya Kulkarni",
    studentEmail: "shreya.kulkarni@email.com",
    partnerName: "Study Abroad Co",
    counsellorName: "Kavita Nair",
    university: "University of Bath",
    program: "MSc Management",
    intake: "Jan 2026",
    stage: "Enrolled",
    submittedAt: "2024-12-05",
  },
];
