import type { UniversityTableRow } from "./types";

/**
 * Seed data — totals: 20 rows, 15 active, 5 inactive, 7 countries, programs sum 3340.
 * Replace with GET /v1/universities when available.
 */
export const universitiesMockData: UniversityTableRow[] = [
  {
    id: "1",
    name: "University of Edinburgh",
    city: "Edinburgh",
    countryName: "United Kingdom",
    flagEmoji: "🇬🇧",
    type: "Public",
    qsRanking: 22,
    programs: 148,
    status: "ACTIVE",
  },
  {
    id: "2",
    name: "University of Manchester",
    city: "Manchester",
    countryName: "United Kingdom",
    flagEmoji: "🇬🇧",
    type: "Public",
    qsRanking: 32,
    programs: 172,
    status: "ACTIVE",
  },
  {
    id: "3",
    name: "University of Toronto",
    city: "Toronto",
    countryName: "Canada",
    flagEmoji: "🇨🇦",
    type: "Public",
    qsRanking: 21,
    programs: 312,
    status: "ACTIVE",
  },
  {
    id: "4",
    name: "McGill University",
    city: "Montreal",
    countryName: "Canada",
    flagEmoji: "🇨🇦",
    type: "Public",
    qsRanking: 30,
    programs: 268,
    status: "ACTIVE",
  },
  {
    id: "5",
    name: "University of Oxford",
    city: "Oxford",
    countryName: "United Kingdom",
    flagEmoji: "🇬🇧",
    type: "Public",
    qsRanking: 3,
    programs: 152,
    status: "ACTIVE",
  },
  {
    id: "6",
    name: "University of Cambridge",
    city: "Cambridge",
    countryName: "United Kingdom",
    flagEmoji: "🇬🇧",
    type: "Public",
    qsRanking: 2,
    programs: 152,
    status: "ACTIVE",
  },
  {
    id: "7",
    name: "Imperial College London",
    city: "London",
    countryName: "United Kingdom",
    flagEmoji: "🇬🇧",
    type: "Public",
    qsRanking: 6,
    programs: 152,
    status: "ACTIVE",
  },
  {
    id: "8",
    name: "University of British Columbia",
    city: "Vancouver",
    countryName: "Canada",
    flagEmoji: "🇨🇦",
    type: "Public",
    qsRanking: 34,
    programs: 152,
    status: "ACTIVE",
  },
  {
    id: "9",
    name: "McMaster University",
    city: "Hamilton",
    countryName: "Canada",
    flagEmoji: "🇨🇦",
    type: "Private",
    qsRanking: 189,
    programs: 152,
    status: "ACTIVE",
  },
  {
    id: "10",
    name: "University of Melbourne",
    city: "Melbourne",
    countryName: "Australia",
    flagEmoji: "🇦🇺",
    type: "Public",
    qsRanking: 14,
    programs: 152,
    status: "ACTIVE",
  },
  {
    id: "11",
    name: "University of Sydney",
    city: "Sydney",
    countryName: "Australia",
    flagEmoji: "🇦🇺",
    type: "Public",
    qsRanking: 19,
    programs: 153,
    status: "ACTIVE",
  },
  {
    id: "12",
    name: "Australian National University",
    city: "Canberra",
    countryName: "Australia",
    flagEmoji: "🇦🇺",
    type: "Public",
    qsRanking: 30,
    programs: 153,
    status: "ACTIVE",
  },
  {
    id: "13",
    name: "Massachusetts Institute of Technology",
    city: "Cambridge",
    countryName: "United States",
    flagEmoji: "🇺🇸",
    type: "Private",
    qsRanking: 1,
    programs: 153,
    status: "ACTIVE",
  },
  {
    id: "14",
    name: "Stanford University",
    city: "Stanford",
    countryName: "United States",
    flagEmoji: "🇺🇸",
    type: "Private",
    qsRanking: 5,
    programs: 153,
    status: "ACTIVE",
  },
  {
    id: "15",
    name: "Harvard University",
    city: "Cambridge",
    countryName: "United States",
    flagEmoji: "🇺🇸",
    type: "Private",
    qsRanking: 4,
    programs: 153,
    status: "ACTIVE",
  },
  {
    id: "16",
    name: "Technical University of Munich",
    city: "Munich",
    countryName: "Germany",
    flagEmoji: "🇩🇪",
    type: "Public",
    qsRanking: 28,
    programs: 153,
    status: "INACTIVE",
  },
  {
    id: "17",
    name: "LMU Munich",
    city: "Munich",
    countryName: "Germany",
    flagEmoji: "🇩🇪",
    type: "Public",
    qsRanking: 54,
    programs: 153,
    status: "INACTIVE",
  },
  {
    id: "18",
    name: "Sorbonne University",
    city: "Paris",
    countryName: "France",
    flagEmoji: "🇫🇷",
    type: "Public",
    qsRanking: 60,
    programs: 153,
    status: "INACTIVE",
  },
  {
    id: "19",
    name: "Sciences Po",
    city: "Paris",
    countryName: "France",
    flagEmoji: "🇫🇷",
    type: "Public",
    qsRanking: 242,
    programs: 153,
    status: "INACTIVE",
  },
  {
    id: "20",
    name: "National University of Singapore",
    city: "Singapore",
    countryName: "Singapore",
    flagEmoji: "🇸🇬",
    type: "Public",
    qsRanking: 8,
    programs: 153,
    status: "INACTIVE",
  },
];
