import type { ProgramTableRow } from "./types";

/**
 * Seed data — 25 programs, 20 active / 5 inactive, 8 universities, 3 countries.
 * Replace with GET /v1/programs when available.
 */
export const programsMockData: ProgramTableRow[] = [
  {
    id: "1",
    name: "MSc Computer Science",
    category: "POSTGRADUATE",
    universityName: "University of Manchester",
    countryName: "United Kingdom",
    flagEmoji: "🇬🇧",
    duration: "1 year",
    studyMode: "Full-Time",
    intakes: ["Sep 2025", "Jan 2026"],
    tuitionPerYear: "£28,500/yr",
    status: "ACTIVE",
  },
  {
    id: "2",
    name: "BSc Business Management",
    category: "UNDERGRADUATE",
    universityName: "University of Edinburgh",
    countryName: "United Kingdom",
    flagEmoji: "🇬🇧",
    duration: "3 years",
    studyMode: "Full-Time",
    intakes: ["Sep 2025", "Jan 2026", "May 2026"],
    tuitionPerYear: "£26,000/yr",
    status: "ACTIVE",
  },
  {
    id: "3",
    name: "PhD Artificial Intelligence",
    category: "PHD",
    universityName: "Imperial College London",
    countryName: "United Kingdom",
    flagEmoji: "🇬🇧",
    duration: "4 years",
    studyMode: "Full-Time",
    intakes: ["Oct 2025", "Apr 2026"],
    tuitionPerYear: "£24,800/yr",
    status: "ACTIVE",
  },
  {
    id: "4",
    name: "Diploma in Foundation Studies",
    category: "DIPLOMA",
    universityName: "University of Manchester",
    countryName: "United Kingdom",
    flagEmoji: "🇬🇧",
    duration: "1 year",
    studyMode: "Full-Time",
    intakes: ["Sep 2025"],
    tuitionPerYear: "£18,200/yr",
    status: "ACTIVE",
  },
  {
    id: "5",
    name: "MBA",
    category: "POSTGRADUATE",
    universityName: "University of Toronto",
    countryName: "Canada",
    flagEmoji: "🇨🇦",
    duration: "2 years",
    studyMode: "Full-Time",
    intakes: ["Sep 2025", "Jan 2026"],
    tuitionPerYear: "CAD 58,000/yr",
    status: "ACTIVE",
  },
  {
    id: "6",
    name: "BEng Mechanical Engineering",
    category: "UNDERGRADUATE",
    universityName: "McGill University",
    countryName: "Canada",
    flagEmoji: "🇨🇦",
    duration: "4 years",
    studyMode: "Full-Time",
    intakes: ["Sep 2025"],
    tuitionPerYear: "CAD 42,500/yr",
    status: "ACTIVE",
  },
  {
    id: "7",
    name: "MSc Data Science",
    category: "POSTGRADUATE",
    universityName: "University of British Columbia",
    countryName: "Canada",
    flagEmoji: "🇨🇦",
    duration: "2 years",
    studyMode: "Full-Time",
    intakes: ["Sep 2025", "Jan 2026"],
    tuitionPerYear: "CAD 48,900/yr",
    status: "ACTIVE",
  },
  {
    id: "8",
    name: "PhD Chemistry",
    category: "PHD",
    universityName: "McGill University",
    countryName: "Canada",
    flagEmoji: "🇨🇦",
    duration: "4 years",
    studyMode: "Full-Time",
    intakes: ["Sep 2025", "Jan 2026", "May 2026"],
    tuitionPerYear: "CAD 22,000/yr",
    status: "ACTIVE",
  },
  {
    id: "9",
    name: "Graduate Diploma in Computing",
    category: "DIPLOMA",
    universityName: "University of Toronto",
    countryName: "Canada",
    flagEmoji: "🇨🇦",
    duration: "1 year",
    studyMode: "Part-Time",
    intakes: ["Sep 2025", "Jan 2026"],
    tuitionPerYear: "CAD 35,000/yr",
    status: "ACTIVE",
  },
  {
    id: "10",
    name: "BSc Computer Science",
    category: "UNDERGRADUATE",
    universityName: "University of Melbourne",
    countryName: "Australia",
    flagEmoji: "🇦🇺",
    duration: "3 years",
    studyMode: "Full-Time",
    intakes: ["Feb 2026", "Jul 2026"],
    tuitionPerYear: "AUD 45,000/yr",
    status: "ACTIVE",
  },
  {
    id: "11",
    name: "Master of Public Health",
    category: "POSTGRADUATE",
    universityName: "University of Sydney",
    countryName: "Australia",
    flagEmoji: "🇦🇺",
    duration: "1.5 years",
    studyMode: "Full-Time",
    intakes: ["Mar 2026", "Aug 2026"],
    tuitionPerYear: "AUD 52,000/yr",
    status: "ACTIVE",
  },
  {
    id: "12",
    name: "PhD Biomedical Sciences",
    category: "PHD",
    universityName: "University of Melbourne",
    countryName: "Australia",
    flagEmoji: "🇦🇺",
    duration: "4 years",
    studyMode: "Full-Time",
    intakes: ["Mar 2026"],
    tuitionPerYear: "AUD 38,000/yr",
    status: "ACTIVE",
  },
  {
    id: "13",
    name: "BA Economics",
    category: "UNDERGRADUATE",
    universityName: "University of Sydney",
    countryName: "Australia",
    flagEmoji: "🇦🇺",
    duration: "3 years",
    studyMode: "Full-Time",
    intakes: ["Feb 2026", "Jul 2026"],
    tuitionPerYear: "AUD 44,500/yr",
    status: "ACTIVE",
  },
  {
    id: "14",
    name: "MSc Finance",
    category: "POSTGRADUATE",
    universityName: "University of Edinburgh",
    countryName: "United Kingdom",
    flagEmoji: "🇬🇧",
    duration: "1 year",
    studyMode: "Full-Time",
    intakes: ["Sep 2025", "Jan 2026"],
    tuitionPerYear: "£31,000/yr",
    status: "ACTIVE",
  },
  {
    id: "15",
    name: "LLM International Law",
    category: "POSTGRADUATE",
    universityName: "Imperial College London",
    countryName: "United Kingdom",
    flagEmoji: "🇬🇧",
    duration: "1 year",
    studyMode: "Full-Time",
    intakes: ["Oct 2025"],
    tuitionPerYear: "£34,200/yr",
    status: "ACTIVE",
  },
  {
    id: "16",
    name: "BSc Psychology",
    category: "UNDERGRADUATE",
    universityName: "University of British Columbia",
    countryName: "Canada",
    flagEmoji: "🇨🇦",
    duration: "4 years",
    studyMode: "Full-Time",
    intakes: ["Sep 2025"],
    tuitionPerYear: "CAD 46,000/yr",
    status: "ACTIVE",
  },
  {
    id: "17",
    name: "PhD Economics",
    category: "PHD",
    universityName: "University of Toronto",
    countryName: "Canada",
    flagEmoji: "🇨🇦",
    duration: "5 years",
    studyMode: "Full-Time",
    intakes: ["Sep 2025", "Jan 2026"],
    tuitionPerYear: "CAD 28,000/yr",
    status: "ACTIVE",
  },
  {
    id: "18",
    name: "Diploma in Digital Marketing",
    category: "DIPLOMA",
    universityName: "University of Sydney",
    countryName: "Australia",
    flagEmoji: "🇦🇺",
    duration: "1 year",
    studyMode: "Part-Time",
    intakes: ["Mar 2026", "Aug 2026", "Nov 2026"],
    tuitionPerYear: "AUD 29,500/yr",
    status: "ACTIVE",
  },
  {
    id: "19",
    name: "MSc Renewable Energy",
    category: "POSTGRADUATE",
    universityName: "University of Melbourne",
    countryName: "Australia",
    flagEmoji: "🇦🇺",
    duration: "2 years",
    studyMode: "Full-Time",
    intakes: ["Feb 2026"],
    tuitionPerYear: "AUD 47,800/yr",
    status: "ACTIVE",
  },
  {
    id: "20",
    name: "BArch Architecture",
    category: "UNDERGRADUATE",
    universityName: "McGill University",
    countryName: "Canada",
    flagEmoji: "🇨🇦",
    duration: "5 years",
    studyMode: "Full-Time",
    intakes: ["Sep 2025"],
    tuitionPerYear: "CAD 51,000/yr",
    status: "ACTIVE",
  },
  {
    id: "21",
    name: "MSc Cyber Security",
    category: "POSTGRADUATE",
    universityName: "University of Manchester",
    countryName: "United Kingdom",
    flagEmoji: "🇬🇧",
    duration: "1 year",
    studyMode: "Full-Time",
    intakes: ["Sep 2025", "Jan 2026"],
    tuitionPerYear: "£29,900/yr",
    status: "INACTIVE",
  },
  {
    id: "22",
    name: "PhD Materials Science",
    category: "PHD",
    universityName: "University of British Columbia",
    countryName: "Canada",
    flagEmoji: "🇨🇦",
    duration: "4 years",
    studyMode: "Full-Time",
    intakes: ["Jan 2026"],
    tuitionPerYear: "CAD 24,500/yr",
    status: "INACTIVE",
  },
  {
    id: "23",
    name: "Graduate Certificate in Analytics",
    category: "DIPLOMA",
    universityName: "University of Melbourne",
    countryName: "Australia",
    flagEmoji: "🇦🇺",
    duration: "8 months",
    studyMode: "Part-Time",
    intakes: ["Mar 2026"],
    tuitionPerYear: "AUD 22,000/yr",
    status: "INACTIVE",
  },
  {
    id: "24",
    name: "BA History",
    category: "UNDERGRADUATE",
    universityName: "University of Edinburgh",
    countryName: "United Kingdom",
    flagEmoji: "🇬🇧",
    duration: "3 years",
    studyMode: "Full-Time",
    intakes: ["Sep 2025"],
    tuitionPerYear: "£24,000/yr",
    status: "INACTIVE",
  },
  {
    id: "25",
    name: "MSc Supply Chain",
    category: "POSTGRADUATE",
    universityName: "University of Sydney",
    countryName: "Australia",
    flagEmoji: "🇦🇺",
    duration: "1.5 years",
    studyMode: "Full-Time",
    intakes: ["Feb 2026", "Jul 2026"],
    tuitionPerYear: "AUD 49,200/yr",
    status: "INACTIVE",
  },
];
